### ISSUE TITLE
Substitution variable 1 replace part of substitution variable 2 if var 1 is a prefix of var 2

### ISSUE THREAD

**Issue by d4h0** [LyonSyonII/akin#2] opened 2022-03-23 13:49 UTC
Hi @LyonSyonII,

I just discovered a bug:

```rust
akin! {
  let &foo = [abc];
  let &foobar = [def];
  
  *foo
  *foobar
}
```

The `foo` of `*foobar` gets replaced with `abc`.

**Comment by LyonSyonII** [comment] 2022-03-23 14:44
I completely missed this.  
It's kind of difficult to fix because on how `akin` currently works (treats code as a string and .replace() each variable with the corresponding value), but I'll look into it.

Thanks for pointing it out!

**Comment by d4h0** [comment] 2022-03-23 19:56
So does `akin` actually operate on strings, or was this just a way to describe the approach?

If the former: You could sort the list of identifiers, and then iterate over that list in reverse order. This way, the longest identifier of identifiers with a common prefix would be replaced first, which would fix the problem.

If the later, and it is too difficult to fix: I don't think this would be a big deal if it's mentioned in the documentation.

That being said, the issue resulted in a pretty strange error, without any useful information. Fortunately (after some time), I used `cargo expand` to see what was going on.

**Comment by LyonSyonII** [comment] 2022-03-23 21:00
Added fix and test to version 0.3.1, could you test it with your code and see if it is really solved? If it is I'll close the issue.

**Comment by d4h0** [comment] 2022-03-24 20:31
Sure. It seems, the problem still exist in 0.3.1. Does it work properly for you?

**Comment by d4h0** [comment] 2022-03-24 21:04
Very odd. When I copy your test to my code, it works.

Tomorrow I'll try to figure out what is going on, and to create reproducible example. Maybe the current test is too simple to trigger the problem.

**Comment by LyonSyonII** [comment] 2022-03-24 21:21
If you can, send me the code in question, I'll try to look into what's `akin` generating exactly

**Comment by LyonSyonII** [comment] 2022-03-25 09:15
I think what caused the problem is that I forgot to sort the variables every time one is inserted, so it only worked for the main code (and not in variable values).  
It should work now, new version is 0.3.2.

**Comment by LyonSyonII** [comment] 2022-03-25 10:12
Found the bug cause, it is a problem with the function that finds what variables are used in a code snippet.  
It"ll probably require a refactor of this function, expect it to be solved in a couple of days, as it's a bit tricky to do right.

**Comment by d4h0** [comment] 2022-03-25 14:40
Thanks for the update. Okay, let me know, when I should test the new fix. Knowing about the problem, it's obviously not a problem for me personally anymore (so no need to hurry).

> If you can, send me the code in question, I'll try to look into what's akin generating exactly

The code is pretty complex and uses many external and internal dependencies, therefore I wanted to create a minimal example that reproduces the issue.

**Comment by LyonSyonII** [comment] 2022-03-28 13:31
Refactor done, it should now work on version 0.3.3
I've also added an additional test (it is a real-world example that wasn't working due to this bug).

**Comment by d4h0** [comment] 2022-03-29 18:23
It seems to be fixes. Thanks, @LyonSyonII!

**Comment by LyonSyonII** [comment] 2022-03-29 18:24
Great, finally! I'll close the issue then

**Closed** 2022-03-29 18:24 UTC
Labels: bug
